title:              Félix Trépanier
email:              felix_trep41@yahoo.com
description:        Welcome to my data science blog
author:             Félix Trépanier
baseurl:            ""
url:                "https://felixtrepanier.github.io"

# Social Profiles
twitter_username:   
github_username:    FelixTrepanier
facebook_username:  
instagram_username: realfefe 
linkedin_username:  felix-trepanier

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

  sass:
    sass_dir: _sass
    style: compressed